# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
      CMS_SPACE_ID: ${{ secrets.CMS_SPACE_ID }}
      CMS_TOKEN: ${{ secrets.CMS_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        ref: origin/main
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: git checkout gh-pages
    - run: git reset --hard origin/main
    - run: npm i
    - run: npm run build
    - run: rm -rf .angular/*
    - run: rm -rf src/*
    - run: mv ./dist/roam-n-roost/browser/* .
    - run: git config user.email "automated-build"
    - run: git config user.name "Automated build to deploy"
    - run: git add .
    - run: git commit -m "Build static pages"
    - run: git push -f